### ISSUE TITLE
Hell

### ISSUE THREAD

**Issue by Biostarhill** [biostars/biostar-handbook#121]
Hello- 
the following came up when i tried the efetch command. Based on what happened last time I tried to install it, but with no success. 
All the best

> mihilpatel@Mihils-MacBook-Pro ~/biostar_handbook/unixtut
> $ efetch -db=nuccore -format=fasta -id=AF086833 > AF086833.fa
> -bash: efetch: command not found
> 
> mihilpatel@Mihils-MacBook-Pro ~/biostar_handbook/unixtut
> $ man efetch
> No manual entry for efetch
> 
> mihilpatel@Mihils-MacBook-Pro ~/biostar_handbook/unixtut
> $ conda install efetch
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - efetch
> 
> Current channels:
> 
>   - https://conda.anaconda.org/bioconda/osx-64
>   - https://conda.anaconda.org/bioconda/noarch
>   - https://conda.anaconda.org/conda-forge/osx-64
>   - https://conda.anaconda.org/conda-forge/noarch
>   - https://repo.anaconda.com/pkgs/main/osx-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/osx-64
>   - https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
>     https://anaconda.org
> 
> and use the search bar at the top of the page.
> 
> 
> 
> mihilpatel@Mihils-MacBook-Pro ~/biostar_handbook/unixtut
> $ efetch -db=nuccore -format=fasta -id=AF086833 > AF086833.fa
> -bash: efetch: command not found

**Comment by ialbert** [comment]
That is not how efetch is installed.  

When the main installation is complete (as instructed in the book, efetch will be properly installed).

You will need to follow the instructions on this page:

https://www.biostarhandbook.com/install-software.html

(efetch is not a Unix default tool, hence won't have a manual page)
