### ISSUE TITLE
I've been troubleshooting the install  on Windows 10 and Ubuntu 20 LTS with students and...,

### ISSUE THREAD

**Issue by njbowen** [biostars/biostar-handbook#176]
I've been troubleshooting the install with students on Windows 10 and Ubuntu 20 LTS, 
using the step by step method, it appears to fail somewhere in the conda install or update.  Often it is an https connection error, sometimes due to the student's particular firewall settings, or Norton antivirus app or wifi proxy settings.  The following is the most common error encountered thus far:
conda update -y -n base conda
Collecting package metadata (current_repodata.json): failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/linux-64'

_Originally posted by @njbowen in https://github.com/biostars/biostar-handbook-issues/issues/169#issuecomment-1018830063_

**Comment by ialbert** [comment]
Another user reports a workaround here

https://github.com/biostars/biostar-handbook-issues/issues/157#issuecomment-1014141326

where they will refer to conda issue:

https://github.com/conda/conda/issues/9948#issuecomment-909989810

the potential solution was to do:

    find miniconda3/ -type f -exec touch {} +

once after installing conda and once after installing mamba. If that were to be the valid solution for you I could add that into the install script.

**Comment by ialbert** [comment]
This issue seems generic and common enough to be tracked in a separate issue that I have also linked from the [Step by step installation][step] chapter in the book:

https://github.com/biostars/biostar-handbook-issues/issues/177

[step]: https://www.biostarhandbook.com/step-by-step.html
